### ISSUE TITLE
Upload Files via POST

### ISSUE THREAD

**Issue by rapsli** [kriswallsmith/Buzz#103]
This is probably a really easy one, but I'm just stuck. I want to upload a file to  a service. I don't have a form that is submitted, but rather a (local) URI to that file. I would greatly appreciate a short example. I was already thinking about encoding it to BASE64 and send it, but there must be a nicer way.

**Comment by Nyholm** [comment]
Closing this since it is super old. 
For the record: Browser::submitForm()
