### ISSUE TITLE
request->__toString() doesn't create a valid http request

### ISSUE THREAD

**Issue by dominikzogg** [kriswallsmith/Buzz#116]
Hello @kriswallsmith 

The __toString() method of your request object https://github.com/kriswallsmith/Buzz/blob/master/lib/Buzz/Message/Request.php#L137 doesn't contain a real http request.
1. host is wrong, it containts the protocol, which is false
2. it doesn't ends on \r\n\r\n (one linebreak isn't enough)

Should i write my own method if i need plain request?

Working on a plain socket implementation for "bad" hosters

Regards @dominikzogg

**Comment by Nyholm** [comment]
We do not longer have a request object. Closing this because it is super old.
