### ISSUE TITLE
save cookies beetween requests

### ISSUE THREAD

**Issue by hd-deman** [kriswallsmith/Buzz#120]
is it posible to save cookies beetween Browser requests?
if yes please update docs to how do it. 
tnx.

**Comment by maalicki** [comment]
@kriswallsmith plase update the docs. Yesterday I spent a few hours to figure it out.
If you want to use buzz and share cookie between pages (ex. do login request) use this

        $uri = '/j_security_check';

        $params = [
            'j_username' => 'username'
            'j_password' => 'password
        ];

        $curl = new Curl();
        $curl->setTimeout(60);

        $this->_browser = new Browser();
        $this->_browser->setClient($curl);

        $this->_browser->getClient()->setOption(CURLOPT_COOKIEFILE, 'cookies.txt');
        $this->_browser->getClient()->setOption(CURLOPT_COOKIEJAR, 'cookies.txt');

        $url = self::API_HOST . $uri;

        $response = $this->_browser->submit($url, $params);

this won't work

        $this->_browser = new Browser();
        $this->_browser->setClient($curl);

        $listener = new CookieListener();
        $cokie = new Cookie('cookie.txt');
        $listener->addCookie($cokie);

        $this->_browser->addListener($listener);

**Comment by sensorario** [comment]
up

**Comment by Nyholm** [comment]
I would be happy to review a PR with updated docs. 
Im going to close this due inactivity.
