### ISSUE TITLE
Add Base URL Functionality

### ISSUE THREAD

**Issue by jeremylivingston** [kriswallsmith/Buzz#121]
Is there any interest in adding the ability to specify the base URL for a browser instance?

It would be ideal if you could simply create a Browser with a base URL, then pass relative paths from that point forward. This wouldn't impact backwards compatibility, since you could have this parameter default to null and keep the existing functionality as is.

I envision that the base URL could be the third constructor parameter in Buzz\Browser. From here, the call() function could determine whether it needs to build the URL from the base URL or if it can move forward with the existing functionality.

I see a major benefit to this because it removes the need for developers to build the URLs themselves. Potentially, the developer could have a service that has a base URL specified and could then pass relative URLs from that point forward. This makes different URLs between different environments much less of a concern.

I'd be happy to add this feature. I just wanted to get a gauge of how receptive you were to it.
Thanks!

**Comment by Nyholm** [comment]
That is cool. But as Kris said almost 5 years ago: A middleware is the way to go =)
