### ISSUE TITLE
connection timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by JonnyD** [kriswallsmith/Buzz#174]
I'm getting this when I log in with Facebook using HWIAuthBundle

`request.CRITICAL: Uncaught PHP Exception Buzz\Exception\ClientException: "Connection timed out after 5000 milliseconds" at /home/website/public_html/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php line 29 {"exception":"[object] (Buzz\\Exception\\ClientException: Connection timed out after 5000 milliseconds at /home/website/public_html/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php:29)"} []
[2014-09-23 15:13:18] security.DEBUG: Write SecurityContext in the session [] []`

**Comment by Nyholm** [comment]
Is this still an issue with the latest version?

**Comment by marcu87** [comment]
I still have this problem, is there any fix? (other than the timeout workaround)

**Comment by Nyholm** [comment]
Isn't this an issue with the server? The server takes too long to respond any that is you get a timeout.

**Comment by marcu87** [comment]
I'm using the Symfony HWIOAuthBundle, with the facebook authentication, the same as the author of the question. It actually works perfect. But, if I login / logout a couple of times, I get this error from time to time. 

I guess it is a problem with the server, or with the CURL library, or something related... But I have no clue where to look or what is the thing that is causing the problem.

**Comment by marcu87** [comment]
Finally I found the solution: 

The problem was that on my server I had ipv6 enabled, but not working... so CURL tried to connect to the facebook api using ipv6, and sometimes it switched automatically to ipv4 and worked just fine, but some other times it didn't work...

What I just did was enable ipv6 on my server, and now everything works perfect.

Hope this will help somebody.

**Comment by Nyholm** [comment]
Thank you for getting back with a solution that worked for you. I'm going to close this issue since it is not related to buzz

**Comment by enekochan** [comment]
I was having a similar problem with timeouts while trying to connect to Facebook with HWIOAuthBundle. It had been working for months but suddenly stoped working.

The exception:

```
request.CRITICAL:
Uncaught PHP Exception HWI\Bundle\OAuthBundle\OAuth\Exception\HttpTransportException: "Error while sending HTTP request" at /var/www/vhosts/domain.com/httpdocs/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/AbstractResourceOwner.php line 255
{
"exception":"[object]
(HWI\\Bundle\\OAuthBundle\\OAuth\\Exception\\HttpTransportException(code: 7):
Error while sending HTTP request at /var/www/vhosts/domain.com/httpdocs/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/AbstractResourceOwner.php:255, Buzz\\Exception\\RequestException(code: 7):
Failed to connect to graph.facebook.com port 443: Connection timed out at /var/www/vhosts/domain.com/httpdocs/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php:29)"
} []

```

In resume the error message:

```
Failed to connect to graph.facebook.com port 443: Connection timed out
```

Have tried increasing all the timeout values I could find (in configurable parameters and overwriting fixed values in code), overwriting the HTTP client in HWIOAuthBundle, and everything I could think of but nothing worked. It worked fine in my development machine but not in production server. What worked for me was enabling IPv6 in my CentOS server :) Followed this guide: https://www.cyberciti.biz/faq/rhel-redhat-fedora-centos-ipv6-network-configuration/

Hope it helps :)

**Comment by blackarcanis** [comment]
@marcu87 I don't have IPv6 enabled on my server :/
And I can't enable it (I'm on a Google Cloud Compute Engine, no IPv6 support for now...).
But if my server request only from an IPv4, there's no reason to get a response on IPv6 right ?

**Comment by enekochan** [comment]
@blackarcanis Then you may try forcing IPv4 in cURL at least to discard it's an IPv6 vs IPv4 error:

```
curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
```

**Comment by blackarcanis** [comment]
@enekochan Could be an idea... but how can I force this option (CURL_IPRESOLVE_V4) with HWIOAuthBundle ?
