### ISSUE TITLE
Attempted to call function "curl_init" in Symfony

### ISSUE THREAD

**Issue by dangreen** [kriswallsmith/Buzz#175]
Attempted to call function "curl_init" from namespace "Buzz\Client" in /var/www/vendor/kriswallsmith/buzz/lib/Buzz/Client/AbstractCurl.php line 39.

ubuntu@46:/var/www$ php -v
PHP 5.5.9-1ubuntu4.4 (cli) (built: Sep  4 2014 06:56:34) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**Comment by mlivan** [comment]
I have the same problem.

**Comment by utkarsh2k2** [comment]
I get the same error.
Tried mlivan's solution but I still get the same error

**Comment by otjutt** [comment]
@mlivan Thanks man! :+1: 

@utkarsh2k2 Try:
sudo apt-get install php-curl

**Comment by GolubovicM** [comment]
In my case I was getting error message that curl package was not found so I had to add repo like this:

sudo add-apt-repository ppa:ondrej/php
sudo apt update

**Comment by dsaconrad** [comment]
Hi, 
I am getting the same error, "Attempted to call function "curl_init" from namespace"  but this is with curl installed and enabled, my output from php --ini is as follows:

Configuration File (php.ini) Path: /etc/php/5.6/cli
Loaded Configuration File:         /etc/php/5.6/cli/php.ini
Scan for additional .ini files in: /etc/php/5.6/cli/conf.d
Additional .ini files parsed:      /etc/php/5.6/cli/conf.d/10-mysqlnd.ini,
/etc/php/5.6/cli/conf.d/10-opcache.ini,
/etc/php/5.6/cli/conf.d/10-pdo.ini,
/etc/php/5.6/cli/conf.d/15-xml.ini,
/etc/php/5.6/cli/conf.d/20-calendar.ini,
/etc/php/5.6/cli/conf.d/20-ctype.ini,
/etc/php/5.6/cli/conf.d/20-curl.ini,
/etc/php/5.6/cli/conf.d/20-dom.ini,
/etc/php/5.6/cli/conf.d/20-exif.ini,
/etc/php/5.6/cli/conf.d/20-fileinfo.ini,
/etc/php/5.6/cli/conf.d/20-ftp.ini,
/etc/php/5.6/cli/conf.d/20-gd.ini,
/etc/php/5.6/cli/conf.d/20-gearman.ini,
/etc/php/5.6/cli/conf.d/20-gettext.ini,
/etc/php/5.6/cli/conf.d/20-iconv.ini,
/etc/php/5.6/cli/conf.d/20-imap.ini,
/etc/php/5.6/cli/conf.d/20-json.ini,
/etc/php/5.6/cli/conf.d/20-mbstring.ini,
/etc/php/5.6/cli/conf.d/20-mcrypt.ini,
/etc/php/5.6/cli/conf.d/20-mongodb.ini,
/etc/php/5.6/cli/conf.d/20-mysql.ini,
/etc/php/5.6/cli/conf.d/20-mysqli.ini,
/etc/php/5.6/cli/conf.d/20-pdo_mysql.ini,
/etc/php/5.6/cli/conf.d/20-phar.ini,
/etc/php/5.6/cli/conf.d/20-posix.ini,
/etc/php/5.6/cli/conf.d/20-readline.ini,
/etc/php/5.6/cli/conf.d/20-shmop.ini,
/etc/php/5.6/cli/conf.d/20-simplexml.ini,
/etc/php/5.6/cli/conf.d/20-sockets.ini,
/etc/php/5.6/cli/conf.d/20-sysvmsg.ini,
/etc/php/5.6/cli/conf.d/20-sysvsem.ini,
/etc/php/5.6/cli/conf.d/20-sysvshm.ini,
/etc/php/5.6/cli/conf.d/20-tokenizer.ini,
/etc/php/5.6/cli/conf.d/20-wddx.ini,
/etc/php/5.6/cli/conf.d/20-xmlreader.ini,
/etc/php/5.6/cli/conf.d/20-xmlwriter.ini,
/etc/php/5.6/cli/conf.d/20-xsl.ini,
/etc/php/5.6/cli/conf.d/20-zip.ini

I have even verified that it works by creating a curl request in a new file, and it worked!
This seems to be a problem specific to the code, but I am reaching out to understand if I have missed out anything. I have followed the above procedure to the T.

Looking for any sort of help.
