### ISSUE TITLE
Header Host HTTP/1.0

### ISSUE THREAD

**Issue by gubarazer** [kriswallsmith/Buzz#178]
Hi,

I notice that requests are sending with HTTP/1.0, with a header Host by default. 
The header Host doesn’t exist in HTTP/1.0. However most of web server tolerate it.
Removing the header host and let the protocol version to 1.0 by default is not a good solution because some application expect to see the Host header regardless of the protocol version.
Easy fix will be to set the default protocol version to 1.1.

**Comment by doublejosh** [comment]
:+1: please

**Comment by kriswallsmith** [comment]
See #189.
