### ISSUE TITLE
Curl proxy header size, wrong header position determined with encoding gzip

### ISSUE THREAD

**Issue by oleg-andreyev** [kriswallsmith/Buzz#181]
Wrong positions determined with buzz v0.13 and curl 7.19.7

```
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
```

Result:

```
strlen($raw) == 41500
curl_getinfo($curl, CURLINFO_SIZE_DOWNLOAD) == 10721
strlen($raw) - curl_getinfo($curl, CURLINFO_SIZE_DOWNLOAD) == 30779
curl_getinfo($curl, CURLINFO_HEADER_SIZE) == 1261 (correct)
```

Client config:

```
$this->client->setVerifyPeer(false);
$this->client->setIgnoreErrors(true);
$this->client->setMaxRedirects(0);
$this->client->setOption(CURLOPT_ENCODING, '') //support all encodings
```

CURLINFO_SIZE_DOWNLOAD returning size that was downloaded with `Content-Encoding: gzip`
#156 #128

**Comment by bburnichon** [comment]
I'm afraid that with curl < 7.30.0, there is no way to correctly determine header size. One way to solve the issue would be to detect whether there is a proxy or not and tell about incompatibility with gzipped content.

**Comment by oleg-andreyev** [comment]
Done in old fashioned way:
```
        /**
         * @bug https://github.com/kriswallsmith/Buzz/pull/156
         * @issue https://github.com/kriswallsmith/Buzz/issues/181
         */
        if (strpos($proxiedResponse->getHeader('content-encoding'), 'gzip') !== false) {
            $content = gzdecode($proxiedResponse->getContent());
        } else {
            $content = $proxiedResponse->getContent();
        }
```

+1 for adding this incompatibility to README

**Comment by arnaud-lb** [comment]
Guzzle seems to be using CURLOPT_HEADERFUNCTION / CURLOPT_WRITEFUNCTION in order to receive the header and the body separately: https://github.com/guzzle/guzzle/blob/b65cdda6b0d237f7a47c25414599c5a400fc4b83/src/Handler/CurlFactory.php#L53

**Comment by arnaud-lb** [comment]
https://github.com/kriswallsmith/Buzz/pull/207 is using CURLOPT_HEADERFUNCTION too
