### ISSUE TITLE
Random RequestException

### ISSUE THREAD

**Issue by MikaelLarsson** [kriswallsmith/Buzz#182]
I have built a simple API which when I call from cURL it always responds very quickly.

But when try to call it from my application, I get random errors saying:

Buzz\Exception\RequestException
…\vendor\kriswallsmith\buzz\lib\Buzz\Client\FileGetContents.php64

I don't know how to interpret this. Please help or point me in a direction.

**Comment by MikaelLarsson** [comment]
It turned out that I had my applications routing and filters set up in a way that made the request time out. It would however be nice with an error to be thrown in case of timeout or bad request etc.

**Comment by joaovcarvalho** [comment]
How do you solved this problem ? I'm using Laravel and have no idea how to increase the time of the request.

**Comment by egeloen** [comment]
You can change the timeout thought the client (See https://github.com/kriswallsmith/Buzz/blob/master/lib/Buzz/Client/AbstractClient.php#L9)

**Comment by joaovcarvalho** [comment]
Thanks @egeloen !
