### ISSUE TITLE
Add support for CURLOPT_INFILE for big files

### ISSUE THREAD

**Issue by nud** [kriswallsmith/Buzz#183]
Having CURLOPT_INFILE/CURLOPT_FILE support makes it possible to get/put big files without filling PHP memory. It would be possible by allowing to do $request->setContent() with a $fd and checking for this case in send().

``` php
$fd = fopen ($filename, 'r');
...
curl_setopt ($ch, CURLOPT_PUT, true);
curl_setopt ($ch, CURLOPT_INFILE, $fd); # read content in $fd
curl_exec ($ch);
```

``` php
$fd = fopen($filename, "w");
...
curl_setopt ($ch, CURLOPT_FILE, $fd); # write result in $fd
curl_exec ($ch);
```

**Comment by arall** [comment]
+1

**Comment by Nyholm** [comment]
This is what guzzle calls "sink". It is a real nice feature but it does not fit to a lightweight client like Buzz
