### ISSUE TITLE
when dumping response object, statusCode is null

### ISSUE THREAD

**Issue by poolerMF** [kriswallsmith/Buzz#187]
everything works OK ... but when I dump response object, statusCode,reasonPhrase and other are NULL .. but if I call  method getStatusCode() it return correct data

this should be changed and method parseStatusLine() should by called in setHeaders(), not in getStatusCode() ...

setHeaders() should be:

```
public function setHeaders(array $headers)
{
    parent::setHeaders($headers);

    $this->resetStatusLine();
    $this->parseStatusLine();
}
```

EXAMPLE:

```
$response = $container->get("buzz.browser")->get('http://.......');
dump($response);
$response->getStatusCode();
dump($response);
```

FIRST DUMP:
Response { ▼
  -protocolVersion: null
  -statusCode: null
  -reasonPhrase: null
  -headers: array:7 [▶]
  -content: "{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error"}}"
}

SECOND DUMP:
Response { ▼
  -protocolVersion: 1.1
  -statusCode: 200
  -reasonPhrase: "OK"
  -headers: array:7 [▶]
  -content: "{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error"}}"
}

**Comment by ingro** [comment]
Yep I noticed that too, thanks for the heads-up!

**Comment by Nyholm** [comment]
The response object are about to be removed
