### ISSUE TITLE
file_get_contents not work with https

### ISSUE THREAD

**Issue by dem3trio** [kriswallsmith/Buzz#193]
Hello,

i'm using sonata-media for symfony and it uses Buzz for downloading some files (for example, thumbnails images from youtube).

Youtube is now using https as default, and it makes file_get_contents crash.

The problem is in /lib/Buzz/Client/FileGetContents.php line 60

adding this line before:
$url = str_replace("https", "http", $url);

should fix this, but I don't know if its the better solution.

**Comment by stof** [comment]
file_get_contents should work with https URLs as long as you have the openssl extension (and that it has the proper configuration for its CA file).
What is the error you are getting ?

**Comment by dem3trio** [comment]
file_get_contents(https://i.ytimg.com/vi/Tj75Arhq5ho/hqdefault.jpg): failed to open stream: operation failed

but if I try to use file_get_contents(**http**://i.ytimg.com/vi/Tj75Arhq5ho/hqdefault.jpg) it works

**Comment by dem3trio** [comment]
There is a related issue opened in sonata-media: https://github.com/sonata-project/SonataMediaBundle/issues/759

**Comment by rande** [comment]
I found out the related issue. The capath must be set. See https://github.com/sonata-project/SonataMediaBundle/issues/759#issuecomment-103472614

**Comment by markusguenther** [comment]
I used a different client and that was a easy workaround for me. Curl is a bit better in such things.

```php
	$browser = new Browser();
	$browser->setClient(new Curl());
```

Hope that helps some other guys too.

**Comment by poizon001** [comment]
Hi,
I am getting the same error
file_get_contents(https://www.xyz.com/health/121.json): failed to open stream: operation failed.

I tried to use file_get_contents(http://www.xyz.com/health/121.json) still it does not works.

Please help

**Comment by Nyholm** [comment]
Thank you @rande for explaining the problem and thanks @markusguenther for a workaround. 

@poizon001, please see previous answers.
