### ISSUE TITLE
0.14 *much* slower than 0.13 when used with behat

### ISSUE THREAD

**Issue by haylingsailor** [kriswallsmith/Buzz#196]
We use buzz as part of our BDD process with behat, and we recently noticed a vast slowdown in the time taken to run behat tests of an API implemented in symfony.

We've isolated the cause to the change from buzz 0.13 to 0.14. Our composer.json rule for behat was set to @stable, which has started pulling in 0.14.

When we revert to 0.13, the problem went away. We demonstrated this on a couple of different machines.

I wasn't able to determine the issue. The behat test in question has 158 steps and usually rattles through in roughly a minute, bounded by IO/CPU. With buzz 0.14, then everything still works, but it takes an order of magnitude or more longer to complete the test. Our entire suite of tests usually takes an hour or so, but this change renders the process unworkable.

While running, I can't see very much happening. It's as if it's waiting  - cpu is at just about zero, and there's plenty of memory, and the machine is using an SSD (though there's not much io happening anyway). I couldn't see any other signs of something being wrong. Simply reverting to buzz 0.13, and making no other change to the configuration fixed things.

We're running centos 6.6.

Is there anything else we need to tune or setup to make the new version run as quickly as the old?

**Comment by kriswallsmith** [comment]
The default HTTP protocol version was changed from 1.0 to 1.1… maybe that's causing some behavior to change somewhere in your stack? Please try your test suite with 0.14 and the protocol version set to 1.0 and see if that makes a difference.

**Comment by beberlei** [comment]
Having the same issue, it seems with Buzz v0.15 all my http requests take exactly 5 seconds.

**Comment by Hezion** [comment]
Thank God, i found this issue. After downgrading from dev-master to 0.13 i noticed a massive speedup. This really needs to be addressed.

**Comment by kriswallsmith** [comment]
Everyone here is experiencing this issue while using Behat?

**Comment by peroumal1** [comment]
Hello, 

I also experienced a speed issue with the last stable version (v0.15) and had to downgrade to 0.13. 
In my case, I am not using Behat but I am doing a HTTP request to an external site in a Symfony controller. The URL requested and what it returns is static (so it cannot come from the URL). 

I was able to pinpoint the exact place where the client is taking more time from one version to another. 
It looks like it comes from the `file_get_contents` call in lib/Buzz/Client/FileGetContents.php, which, from my current observations take less than 200ms in 0.13 and around 6s (!) in 0.15. 

Since I am pretty new to this library, did something change on the parameters passed to this function from a version to another ? 

Thanks !

**Comment by kriswallsmith** [comment]
If you change the default HTTP protocol from 1.1 back to 1.0 does that fix
the issue?

**Comment by MinerCrafter** [comment]
I confirm.

For a simple request with the version 0.15 (FileGetContents()) :
HTTP 1.1 : Request takes 10 seconds.
HTTP 1.0 : Request takes less than 500 ms.

Thanks.

**Comment by vinniecent** [comment]
If I'm not mistaken, the HTTP 1.1 protocol uses a persistent connection by default (Connection: Keep-Alive). So the connection has to be explicitly closed or else the connection waits until it is timed-out. I think this can explain why the request is taking so long to complete.

Adding the header 'Connection: close' fixes this issue for me:

``
$headers = array('Connection' => 'close');
``

**Comment by Nyholm** [comment]
I've done some testing with version 0.13, 0.14 and master. I've been using Blackfire, PHP 7.1, local PHP server and remote server. I've been using both CurlClient and FileGetContents.

I cannot find the performance issue mentioned here. I can only find smaller variation in performance where the biggest is 20%. Which sounds massive but when 20 requests on average takes 800ms or 950ms it is kind of the same... It is anyhow the issue related to what mentioned here.

**Comment by Nyholm** [comment]
Im closing this due inactivity.
