### ISSUE TITLE
MultiCurl: Allow to set a default callback

### ISSUE THREAD

**Issue by maryo** [kriswallsmith/Buzz#206]
I'd like to set a default callback for each request using MultiCurl. Not sure this is the best way but it does the trick and keeps the same interface. I can create a PR which would add something like this (hardcoded to the original MultiCurl - without the inheritance OFC ). Or is there a better way?

https://github.com/vaniocz/VanioBuzzBundle/blob/master/Buzz/MultiCurl.php
Why do I need this?

When using MultiCurl, all listeners' `postSend` methods are invoked before the requests are really performed - the responses are not populated so the `postSend` methods are actually useless.

I solved it this way using a special ListenerChain which is aware of the client. But it needs to either be able to set a default multicurl callback or to override the options being used for each request like in this issue - https://github.com/kriswallsmith/Buzz/issues/168

The best would be both :)

https://github.com/vaniocz/VanioBuzzBundle/blob/master/Buzz/BatchListenerChain.php

**Comment by Nyholm** [comment]
Oh, this is interesting. I'll see what I can do.
