### ISSUE TITLE
Setting cURL options

### ISSUE THREAD

**Issue by mcbuckets** [kriswallsmith/Buzz#208]
Is there a way to set cURL client options rather than instantiating Curl class and setting every option manually via setOption() method? This seems kind of messy. Are PR's addressing this concern welcome?

**Comment by Nyholm** [comment]
The browser should be able to do a “proxy” call to the client’s withAddedOptions.

**Comment by Nyholm** [comment]
Okey. So this is how we should do it: We should allow a second parameter on `Browser::sendRequest()` to allow `$settings`. 

Ping @georgosXL, is that something you can look at?

**Comment by GeorgosXL** [comment]
@Nyholm yes, definitely 👍

**Comment by Nyholm** [comment]
Closed by #285
