### ISSUE TITLE
ListenerInterface is missing a exception event

### ISSUE THREAD

**Issue by arnaud-lb** [kriswallsmith/Buzz#212]
In Browser, postSend() is not called when the client throws an exception: https://github.com/kriswallsmith/Buzz/blob/d4041666c3ffb379af02a92dabe81c904b35fab8/lib/Buzz/Browser.php#L130

This makes the Listener interface less useful for a number of use-cases. For instance, in a logging or tracing listener, it would be useful to be able to log errors.

**Comment by Nyholm** [comment]
This is fixed in master.
