### ISSUE TITLE
cURL installed, still getting undefined function curl_init in \Buss\Client\AbstractCurl.php

### ISSUE THREAD

**Issue by IzaacJ** [kriswallsmith/Buzz#214]
Got this error:
`Call to undefined function Buzz\Client\curl_init() in /[path]/Buzz/Client/AbstractCurl.php on line 39`

Reinstalled php5-curl but still getting this error.

curl information:

```
cURL support => enabled
cURL Information => 7.35.0
Age => 3
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => Yes
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => No
SSL => Yes
SSPI => No
TLS-SRP => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, smtp, smtps, telnet, tftp
Host => x86_64-pc-linux-gnu
SSL Version => OpenSSL/1.0.1f
ZLib Version => 1.2.8

```

**Comment by Hast** [comment]
Can you provide a snippet of code you run?

**Comment by IzaacJ** [comment]
It's when using bitbucket-api: https://bitbucket.org/gentlero/bitbucket-api

Got Buzz and the bitbucket-api to work flawlessly on a VM with the same setup (initial AMP stack), which is kind of weird.
Will search for any packages that might differ between the setups.

**Comment by stof** [comment]
being able to install `php5-curl` without `libcurl` looks weird to me. The package manager should be handling dependencies.
