### ISSUE TITLE
SSL certificate problem: certificate is not yet valid

### ISSUE THREAD

**Issue by severin-bruhat** [kriswallsmith/Buzz#222]
hi,
Since one week i have this error on my test environment when I try to login with Google (HWIOAuthBundle):

Error while sending HTTP request
500 Internal Server Error - HttpTransportException
HttpTransportException: Error while sending HTTP request
RequestException: SSL certificate problem: certificate is not yet valid
in vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php at line 29

I don't understand what's happening because it worked well a few minutes before and it is still working on the live environment.
What is this SSL certificate issue, I don't even have a SSL certificate on this environment...

Thank you for your help

**Comment by stof** [comment]
Well, the SSL certificate is on the server you are contacting with Buzz (so probably a Google server in your case)

**Comment by severin-bruhat** [comment]
what is weird is that it is working on my production (live) environment, and it is the same source code. and i don't find anything on google, it is like I am the only one having this issue....

**Comment by severin-bruhat** [comment]
I found the solution here : http://stackoverflow.com/questions/41581507/curl-error-60-ssl-certificate-problm-certificate-is-not-yet-valid-lemp-wordpr
My server's date/time was not correct, so i installed NTP
