### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by valetanddama** [kriswallsmith/Buzz#225]
Hi. I get error

> Uncaught PHP Exception Buzz\Exception\RequestException: "SSL certificate problem: certificate has expired" at vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php line 29

**Comment by stof** [comment]
you should report it to the owner of the website which you try to access. Buzz is not the source of the issue here. It is the one telling you that the SSL certificate of the target server is not valid.
