### ISSUE TITLE
Cannot parse odd response header

### ISSUE THREAD

**Issue by Azenet** [kriswallsmith/Buzz#239]
Hello,

I have an issue with a web service that returns a weird `HTTP/1.1 200` header without the "OK" part. This makes Buzz fail to parse the status code since it expects the status word. Obviously the web service should be fixed to return compliant headers, however clients like cURL seem to support fixing it, so should Buzz try parsing invalid headers?

**Comment by Nyholm** [comment]
Thank you for this issue. 

This is fixed in the latest release tagged a few days ago.
