### ISSUE TITLE
What is an appropriate way to catch timeout exception ?

### ISSUE THREAD

**Issue by PezCoder** [kriswallsmith/Buzz#247]
- [x] Look through similar issues in the repo before creating this issue

#### What ? 
I'm trying to find how can I properly handle (catch) timeout exception thrown by buzz.
Ways:
1. [Bad one] Using `\Exception`
```
try {
  // some wrapper which calls buzz & times out
} catch (\Exception $e) {
    var_dump($e->getCode());
}
Output: 28
```
This is bad because any exception even runtime code exceptions would get into this which we don't generally want.

2. [Good one] Using `ClientException`
```
use Buzz\Exception\ClientException;
try {
  // some wrapper which calls buzz & times out
} catch (ClientException $e) {
    var_dump($e->getCode());
}
Output: 28
```
Timeout exception gets catch inside this `ClientException` catch block

#### I want to know
1. Why is the status code 28 for a timeout exception, shouldn't this be 504 ?
2. Is catching it with ClientException recommended approach ?

**Comment by Nyholm** [comment]
1) You cannot get a 5xx response if the process timed out... Because a timeout means "no response". 

2) I think so, yes. It is however unclear. I will introduce a `NetworkException` that is used for timeouts.

**Comment by PezCoder** [comment]
Ah, you're right 5xx shouldn't be the response, 28 works for now.
Is there a pr or issue where I can track the progress of `NetworkException` ?

**Comment by Nyholm** [comment]
Not atm. We are soon (in December) to implement psr18 which require such exception.
