### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by ozzmaster** [kriswallsmith/Buzz#250]
I get this deprecation warning when I try to post using this bundle:

The ability to pass file names to the Symfony\Component\Yaml\Yaml::parse method is deprecated since version 2.2 and will be removed in 3.0. Pass the YAML contents of the file instead.

/~/src/IGA/UserBundle/Services/OauthManager.php(115): Buzz\Client\FileGetContents->send(Object(Buzz\Message\Form\FormRequest), Object(Buzz\Message\Response))

Here is my code:

```
$formRequest = new FormRequest(FormRequest::METHOD_POST, '/api/uri?access_token=' . $config['access_token'], 'http://localhost');
$formRequest->addFields(array('data' => json_encode(array('var1' => 'val1')));
$responseBrowser = new Response();

$client = new FileGetContents();

$client->send($formRequest, $responseBrowser);
```
What am I doing wrong? Is there a better way to post data?

**Comment by Nyholm** [comment]
I think you sent the issue to the wrong repository. We do not use the Symfony\Yaml component at all.. 

You should investigate more closely what is happening at `/~/src/IGA/UserBundle/Services/OauthManager.php(115)`
