### ISSUE TITLE
Replacement for Buzz\Listener\ListenerInterface?

### ISSUE THREAD

**Issue by craigcarnell** [kriswallsmith/Buzz#274]
In a PR Listeners were moved out - but i'm not sure where to find these?

use Buzz\Listener\ListenerInterface as BuzzListenerInterface;

I'm also seeing this:

```
Warning: include(Buzz\Browser.php): failed to open stream: No such file or directory
```

The only change was to update the module.

I did add to composer.json as requested:
```
"psr/http-client": "dev-master"
```

Thank you

**Comment by Nyholm** [comment]
I see that you are using dev-master. Listeners are replaced by `Middlewares`. See https://github.com/kriswallsmith/Buzz/tree/master/lib/Buzz/Middleware

**Comment by craigcarnell** [comment]
@Nyholm Thanks - now using a version instead of master

**Comment by Nyholm** [comment]
Yeah that would be better. 

There are quite a few changes from 0.16.1 to 0.17.0. They will be properly documented before we release a new version.
