### ISSUE TITLE
Hotfix for try..catch in Buzz\Client\Curl.php for Buzz Version 0.16.1

### ISSUE THREAD

**Issue by LegendOfGIT** [kriswallsmith/Buzz#319]
Hi Kris,

in our production code, we are using the version 0.16.1 of your Buzz Browser with the Curl client.
Since the timeout handling from version 0.17.0 isn't released yet, we are not able to handle timeouts in our health-check component gently.

Do you have enough capacity to release the try..catch for curl_exec as a hotfix in version 0.16.2.

This would be great.

Otherwise, can you approximate the date of release for version 0.17.0?

**Comment by Nyholm** [comment]
Hey. 

You may set timeout in 0.17.0.  =) It is even a featured example in the docs. See https://github.com/kriswallsmith/Buzz/blob/master/doc/client.md

> Otherwise, can you approximate the date of release for version 0.17.0?

It was released earlier this week.

**Comment by LegendOfGIT** [comment]
Sorry.
I am confused.

In the Release Notes of 0.17.0, you are saying that 0.17.0 is not released yet:
https://github.com/kriswallsmith/Buzz/blob/v0.17.0/CHANGELOG.md

If i update via composer, "kriswallsmith/buzz": "> 0.6" updates only on version 0.16.1.

**Comment by Nyholm** [comment]
No worries. 

The link you are giving me is to the v0.17 version of the docs. =) Check the master version of the docs. 

> If i update via composer, "kriswallsmith/buzz": "> 0.6" updates only on version 0.16.1.

It may be other things restring you from upgrading. Version 0.17 is requiring PHP7.1 or above.

**Comment by LegendOfGIT** [comment]
Ok.
This is definitly a show stopper.
We can't update our product on PHP7.1 from one day to the other.

In this case, it would be pretty neat, if you release a hotfix of version 0.16.1 with the try..catch for curl_exec.

**Comment by Nyholm** [comment]
Yeah, I understand that. 

Sure, I do not see a reason why we could not do a 0.16.2. I've created a 0.16.x branch. Feel feel free to submit a PR.

**Comment by LegendOfGIT** [comment]
Allright.
Thx.
I will prepare a PR.

**Comment by LegendOfGIT** [comment]
To be honest.
This test-server for integration tests is a huge obstacle for contributors on your project.
It's absolutely painful to setup the execution with docker.

I would genuinely be thankful if you take a bit of you're time to apply the try..catch improvement on version 0.16.1

**Comment by LegendOfGIT** [comment]
Jep.
Had the same travis thought.

I will think about an alternative for the test-server.
I know this is straight forward.
But one have to perform a trickshot to use it in docker without php installation.

**Comment by stof** [comment]
Well, if you have a Docker container with PHP installed in it, you could as well run the 3 commands inside the container

**Comment by LegendOfGIT** [comment]
@stof
I tried man.
But sadly i hadn't had the time to finish the setup.
Could you add a docker-compose.yml to this repository?

**Comment by Nyholm** [comment]
I've added a docker image for testing. See readme in in master.
