### ISSUE TITLE
RFC Constructor argument order

### ISSUE THREAD

**Issue by Nyholm** [kriswallsmith/Buzz#335]
Currently we have: 
`AbstractClient::__construct(array $options, ResponseFactoryInterface $factory)`

The second argument has recently been made mandatory. I think it would make sense to flit the order. Since the option array is not always used. 

I propose: 
`AbstractClient::__construct(ResponseFactoryInterface $factory, array $options = [])`

**Comment by gpietoso** [comment]
Curiosity: which RFC?

**Comment by Nyholm** [comment]
I just meant "Request For Change"
