### ISSUE TITLE
error getSession()

### ISSUE THREAD

**Issue by carlosnewmusic** [kriswallsmith/Buzz#353]
https://github.com/kleiram/transmission-php/issues/80#issue-383625520

https://github.com/kleiram/transmission-php/issues/80

**Comment by Nyholm** [comment]
https://github.com/kleiram/transmission-php/blob/1.0.0/composer.json#L14

**Comment by carlosnewmusic** [comment]
> 
> 
> https://github.com/kleiram/transmission-php/blob/1.0.0/composer.json#L14

I know, that is installed but still gives error in your module

**Comment by carlosnewmusic** [comment]
> 
> 
> The library you refer to does not have the proper version constraints. Make sure you install another version of buzz and you will be fine. Try with 0.9.0
Would it be something like that, no?
![imagen](https://user-images.githubusercontent.com/19379457/49098341-f4ab6e00-f26e-11e8-827f-4f58fc6fcd60.png)

**Comment by Nyholm** [comment]
Sure. Or just add something like that in your application’s composer.json

**Comment by carlosnewmusic** [comment]
> Sure. Or just add something like that in your application’s composer.json
it keeps giving the same error
![imagen](https://user-images.githubusercontent.com/19379457/49101812-756e6800-f277-11e8-9f57-1c7cfa26248d.png)

**Comment by Nyholm** [comment]
Try a different version then. Try 0.15 or something between that and 0.9. 
I don’t know that library you are using. Sorry :/

**Comment by carlosnewmusic** [comment]
> 
> 
> Try a different version then. Try 0.15 or something between that and 0.9.
> I don’t know that library you are using. Sorry :/

![imagen](https://user-images.githubusercontent.com/19379457/49463481-c1ca2280-f7f8-11e8-9a1d-f93d3f1dc049.png)
![imagen](https://user-images.githubusercontent.com/19379457/49463496-d60e1f80-f7f8-11e8-8c22-20aad7ba9e7e.png)
![imagen](https://user-images.githubusercontent.com/19379457/49463750-81b76f80-f7f9-11e8-816d-e5090b087b71.png)
