### ISSUE TITLE
CookieMiddleware Incorrect separation of cookies in Cookie header

### ISSUE THREAD

**Issue by Tetragramat** [kriswallsmith/Buzz#391]
Correct separation of multiple cookies in Cookie header is `;`, but `,` is used instead.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie#Syntax

Incorrect assert in test:
https://github.com/kriswallsmith/Buzz/blob/master/tests/Unit/Middleware/Cookie/CookieJarTest.php#L60

**Comment by kids-return** [comment]
https://github.com/kriswallsmith/Buzz/blob/62422cbbd17efa757353116d42508fda8503c754/lib/Middleware/Cookie/CookieJar.php#L51

```php
    /**
     * Adds Cookie headers to the supplied request.
     */
    public function addCookieHeaders(RequestInterface $request): RequestInterface
    {
        $cookies = [];
        foreach ($this->getCookies() as $cookie) {
            if ($cookie->matchesRequest($request)) {
                $cookies[] = $cookie->toCookieHeader();
            }
        }
        if ($cookies) {
            $request = $request->withAddedHeader('Cookie', implode('; ', $cookies));
        }

        return $request;
    }
```
This is the right thing to do here.

**Comment by Nyholm** [comment]
Thank you @kids-return I will prepare a PR with this fix
