### ISSUE TITLE
Comments lie in HeaderConverter

### ISSUE THREAD

**Issue by psren** [kriswallsmith/Buzz#396]
The comments are not saying what the method does but the opposite.

https://github.com/kriswallsmith/Buzz/blob/master/lib/Message/HeaderConverter.php#L24-L27
https://github.com/kriswallsmith/Buzz/blob/master/lib/Message/HeaderConverter.php#L44-L47

I'd provide a PR if you want and swap the two comments.
Which is the correct branch to base on?

**Comment by Nyholm** [comment]
Oh, you are correct. Make a PR from master
