### ISSUE TITLE
[CurlClient] Work when open_basedir is set

### ISSUE THREAD

**Issue by joksnet** [kriswallsmith/Buzz#40]
The problem came from the curl option `CURLOPT_FOLLOWLOCATION` that it doesn't work well with `open_basedir` directive.

The PHP Warning is triggered:

```
Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set in /home/http/symfony/vendor/buzz/lib/Buzz/Client/Curl.php line 138
```

As [`open_basedir`](http://www.php.net/manual/en/ini.core.php#ini.open-basedir) it's a good security practice, would be great if Buzz can work with it.

**Comment by Nyholm** [comment]
Closing this since it is super old.
