### ISSUE TITLE
A release supporting PHP 8?

### ISSUE THREAD

**Issue by someniatko** [kriswallsmith/Buzz#418]
I see, semi-recently a PR was merged for adding PHP 8 support. However, I guess, an HTTP Push problem was unresolved. Is it feasible to wait for a release supporting PHP 8 in the near future?

**Comment by tuupola** [comment]
Any news about this?

**Comment by sunkan** [comment]
@Nyholm Can you take a look at this

**Comment by Nyholm** [comment]
Thank you for the ping. Sure, will do.

**Comment by Nyholm** [comment]
Here we go: https://github.com/kriswallsmith/Buzz/releases/tag/1.2.0
