### ISSUE TITLE
Error handling abstraction

### ISSUE THREAD

**Issue by igorw** [kriswallsmith/Buzz#43]
Right now Buzz has a ignoreErrors setting on the client which can disable errors from being shown. However it does not really abstract the errors. In most cases an error would simply result in a notice, which is not nice.

It would be great if the user could expect a certain exception to be thrown in case of an error. Some Buzz\Client\Exception or similar.

**Comment by Nyholm** [comment]
Closing this since it is super old. We will move towards PSR18 which specify how errors should be handled.
