### ISSUE TITLE
Missing mutual authentication methods

### ISSUE THREAD

**Issue by dinamic** [kriswallsmith/Buzz#63]
I've found out that implementing mutual authentication using Buzz is quite impossible.

We need to be able to set path to the ssl certificate, ssl private key and ssl certificate authority list. I guess Passing direct options to the Curl would not be possible, due to the fact that you use adapters, which might mean that you plan on adding support for different clients later on.

**Comment by Nyholm** [comment]
I think this could be done with Middlewares. 

Im closing this issue since it is super old.
