### ISSUE TITLE
Wrong assumptions

### ISSUE THREAD

**Issue by acidChrist** [kriswallsmith/Buzz#94]
Hi Kris,

I had really strange situation in order to use your library. The problem doesn't exists when curl send request to server with linux on the board and apache. Problems appear when curl send request to server with windows server on the board and IIS7. I found the issue and it looks like you use CURLOPT_CUSTOMREQUEST to set up METHOD for every kind what is wrong from IIS point of view and following definition:
- CURLOPT_CUSTOMREQUEST : A custom request method to use instead of "GET" or "HEAD" when doing a HTTP request. This is useful for doing "DELETE" or other, more obscure HTTP requests.

Using the option as POST makes a lot of problems and is really hard to debug. You should use definitely CURLOPT_POST for posts requests instead of CURLOPT_CUSTOMREQUEST. I read your code and looks like you have to change assumptions a bit.

V

**Comment by Nyholm** [comment]
Closing this since it is super old.
