### ISSUE TITLE
Post not working in file_get_contents client

### ISSUE THREAD

**Issue by ChristianRiesen** [kriswallsmith/Buzz#96]
I wanted to do a simple test. Send out a post  to another location. It calls a file that is simply doing a print_r on $_POST.

``` php
$browser = new Buzz\Browser();
$response = $browser->post('http://test', array(), array('id' => 123, 'name' => 'tester'));

echo $response;
```

Returns
HTTP/1.1 200 OK
Date: Sat, 29 Sep 2012 03:48:57 GMT
Server: Apache
X-Powered-By: PHP/5.3.10-1ubuntu3.2
Vary: Accept-Encoding
Content-Length: 10
Connection: close
Content-Type: text/html

Array
(
)

``` php
$browser = new Buzz\Browser(new Buzz\Client\Curl());
$response = $browser->post('http://test', array(), array('id' => 123, 'name' => 'tester'));

echo $response;

```

Returns

HTTP/1.1 200 OK
Date: Sat, 29 Sep 2012 04:07:01 GMT
Server: Apache
X-Powered-By: PHP/5.3.10-1ubuntu3.2
Vary: Accept-Encoding
Content-Length: 47
Content-Type: text/html

Array
(
    [id] => 123
    [name] => tester
)

The inconsistency is in the handling of the request content on post. I can see curl is handling this with a switch, but there is no equivalent on file_get_contents. Is this a limitation of file_get_contents itself I'm unaware of or simply not fully implemented?

**Comment by Nyholm** [comment]
Closing this since it is super old.
