### ISSUE TITLE
Easy/best way to do unit tests

### ISSUE THREAD

**Issue by itavero** [kriswallsmith/Buzz#98]
I was wondering what would be the best way to perform unit tests on a webservice client built using Buzz.
I reckon I should write some "mock data" client, so that the test does not require an internet connection and returns a response we can depend on (so that are tests won't fail if the webservice is unreachable).

What are your opinions on this and has anyone been working on this before?

**Comment by Nyholm** [comment]
The php-http/mock-client could be interesting for you. 

Im closing this since it super old.
